language: Python
 
 sudo: required
 
 services:
   - docker
 
 branches:
   only:
     - master
 
 before_install:
     - docker version
     - python --version
 
 install:
     - git clone https://github.com/kbase/jars
     - git clone https://github.com/kbase/kb_sdk
     - cd kb_sdk
     - make
     - make sdkbase
     - docker images
     - export PATH=$(pwd)/bin:$PATH
     - cd ../
 
 script:
   - kb-sdk validate 